package com.example.mywatchface

const val RGB_POSSIBLE_VALUES = 256
const val ALPHA = 255
const val ZERO_FLOAT = 0f
const val INTERACTIVE_UPDATE_RATE_MS = 1000
const val MSG_UPDATE_TIME = 0
const val HOUR_STROKE_WIDTH = 5f
const val MINUTE_STROKE_WIDTH = 3f
const val SECOND_TICK_STROKE_WIDTH = 2f
const val CENTER_GAP_AND_CIRCLE_RADIUS = 4f
const val SHADOW_RADIUS = 6f
const val HOURS_IN_ANALOG_CLOCK = 12
const val MILLISECONDS = 1000f
val HOURS = 0..11
const val FRACTION_ANGLE = 6f
const val OFFSET = 30
const val HOUR_HAND_OFFSET = 2f
const val ONE_ROUND = Math.PI * 2.0
const val INNER_TICK_RADIUS_OFFSET = 10
const val SECONDS_HAND_LENGTH = 0.875
const val MINUTES_HAND_LENGTH = 0.75
const val HOURS_HAND_LENGTH = 0.5
const val MIDDLE = 2f
const val SECONDS_ALPHA = 80
const val MINUTES_ALPHA = 100
const val HOURS_ALPHA = 100
const val ACTIVE = true
const val INACTIVE = false
const val CENTER_CIRCLE = 0f
const val MARGIN_DRAW_BITMAP = 0f